import os
os.system("echo")
os.system("echo 'Elitist Setup'")
os.system("echo '==============='")
os.system("echo")
os.system("pip install -r scripts/assets/requirements.txt")
os.system("npm install")
os.system("python server/manage.py makemigrations")
os.system("python server/manage.py migrate")
os.system("python server/manage.py loaddata server/fixtures/initial_data.json")
os.system("echo")
os.system("echo 'Setup Complete.'")
os.system("echo")
os.system("echo 'Django admin username: admin'")
os.system("echo 'Django admin password: admin'")
os.system("echo 'Make sure to change these in production.'")
os.system("echo")
os.system("echo 'To run the server, type: npm run server'")
os.system("echo")
